# Specify if several system configurations can be found in the data directory and
# should be scanned for.
#system_copy = false
#system_scan = true

# If scanning for systems, the systems may be configured to be flat, expecting config files to be
# placed in the systems root directory
#system_flat = true

[directories]
# The directory of necessary library files
lib_dir = "/var/lib/puma/"

# The directory for temporary files
tmp_dir = "/var/tmp/puma/"

# The writable directory where configurations may be found or results will be stored in
data_dir = "/var/opt/puma/"
